In [29]:
import pandas as pd
import os

# Directory containing the CSV files
csv_dir = "C:/Users/Admin/Desktop/Lab Exam/86955_Python_R_programming/Final csv"

# List to store DataFrames
dataframes = []

# Iterate through all CSV files in the directory
for file in os.listdir(csv_dir):
    if file.endswith(".csv"):
        print(file)
        file_path = os.path.join(csv_dir, file)
        df = pd.read_csv(file_path)
        dataframes.append(df)
# print(dataframes)
combined_df = pd.concat(dataframes, ignore_index=True)

output_file = "combined_data.csv"
combined_df.to_csv(output_file, index=False)

print(f"Combined CSV saved")

apple_with_ratings_and_feature_hrefs.csv
Asus_with_ratings_and_feature_hrefs.csv
Honor_with_ratings_and_feature_hrefs.csv
HTC_with_ratings_and_feature_hrefs.csv
Infinix_with_ratings_and_feature_hrefs.csv
iQ_with_ratings_and_feature_hrefs.csv
Itel_with_ratings_and_feature_hrefs.csv
Karbon_with_ratings_and_feature_hrefs.csv
Lava_with_ratings_and_feature_hrefs.csv
Lenovo_with_ratings_and_feature_hrefs.csv
Micromax_with_ratings_and_feature_hrefs.csv
Motorola_with_ratings_and_feature_hrefs.csv
NOKIA_with_ratings_and_feature_hrefs.csv
Nothing_with_ratings_and_feature_hrefs.csv
OnePlus_with_camera_ratings_and_comments.csv
Oppo_with_ratings_and_feature_hrefs.csv
Poco_with_ratings_and_feature_hrefs.csv
Realme_with_ratings_and_feature_hrefs.csv
Redmi_with_ratings_and_feature_hrefs.csv
Sony_with_ratings_and_feature_hrefs.csv
Techno_with_ratings_and_feature_hrefs.csv
Vivo_with_ratings_and_feature_hrefs.csv
Combined CSV saved

In [30]:
df.shape

(372, 37)

In [2]:
import numpy as np
df = pd.read_csv("combined_data.csv")
df.head(2)

,Product Name,Rating,Rating Count,Information,Price,href,5_star,4_star,3_star,2_star,...,Display_Negative_Score,Display_Comments,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments
0,"Apple iPhone 15 (Black, 128 GB)",4.6,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...","₹57,999",https://www.flipkart.com/apple-iphone-15-black...,"1,11,018","16,956","3,770","1,923",...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...","₹57,999",https://www.flipkart.com/apple-iphone-15-pink-...,"1,11,018","16,956","3,770","1,923",...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."

In [3]:
columns_to_remove = ['href','Camera_href', 'Battery_href', 'Display_href',  'Design_href', 'overall_href', 'performance_href']
df.drop(columns=columns_to_remove, inplace=True)
df.head(2)

,Product Name,Rating,Rating Count,Information,Price,5_star,4_star,3_star,2_star,1_star,...,Display_Negative_Score,Display_Comments,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments
0,"Apple iPhone 15 (Black, 128 GB)",4.6,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...","₹57,999","1,11,018","16,956","3,770","1,923","6,310",...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...","₹57,999","1,11,018","16,956","3,770","1,923","6,310",...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."

In [4]:
df['Price'] = df['Price'].str.replace('₹','', regex=False)
df['Price'] = df['Price'].str.replace(',','', regex=False)
df['Price'] = pd.to_numeric(df['Price'])
df.head(2)

,Product Name,Rating,Rating Count,Information,Price,5_star,4_star,3_star,2_star,1_star,...,Display_Negative_Score,Display_Comments,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments
0,"Apple iPhone 15 (Black, 128 GB)",4.6,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923","6,310",...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923","6,310",...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."

In [5]:
import pandas as pd
import re

# Function to extract ratings and reviews
def extract_ratings_reviews(row):
    # Extract ratings
    ratings_match = re.search(r'([\d,]+) Ratings', row)
    ratings = int(ratings_match.group(1).replace(',', '')) if ratings_match else 0
    
    # Extract reviews
    reviews_match = re.search(r'([\d,]+) Reviews', row)
    reviews = int(reviews_match.group(1).replace(',', '')) if reviews_match else 0
    
    return pd.Series({'Rating_count': ratings, 'Review_count': reviews})

# # Example DataFrame
# data = {'Details': ['1,39,977 Ratings & 4,510 Reviews', '5,000 Ratings & 350 Reviews']}
# df = pd.DataFrame(data)

# Apply the function to create new columns
df[['Rating_count', 'Review_count']] = df['Rating Count'].apply(extract_ratings_reviews)

df.head(2)

,Product Name,Rating,Rating Count,Information,Price,5_star,4_star,3_star,2_star,1_star,...,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments,Rating_count,Review_count
0,"Apple iPhone 15 (Black, 128 GB)",4.6,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923","6,310",...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ...",139977,4510
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923","6,310",...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ...",139977,4510

In [6]:
df.insert(2, "Rating_counts", df['Rating_count'])
df.head()

,Product Name,Rating,Rating_counts,Rating Count,Information,Price,5_star,4_star,3_star,2_star,...,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments,Rating_count,Review_count
0,"Apple iPhone 15 (Black, 128 GB)",4.6,139977,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923",...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ...",139977,4510
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,139977,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923",...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ...",139977,4510
2,"Apple iPhone 15 (Green, 128 GB)",4.6,139977,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923",...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ...",139977,4510
3,"Apple iPhone 15 (Blue, 128 GB)",4.6,139977,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",58249,"1,11,018","16,956","3,770","1,923",...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ...",139977,4510
4,"Apple iPhone 15 Plus (Blue, 128 GB)",4.6,21881,"21,881 Ratings & 1,151 Reviews","['128 GB ROM', '17.02 cm (6.7 inch) Super Reti...",66999,"17,326","2,833",544,261,...,4.6,97%,3%,['N/A'],Error,Error,Error,Error,21881,1151

In [7]:
df.insert(3, "Review_counts", df['Review_count'])
df.head(2)

,Product Name,Rating,Rating_counts,Review_counts,Rating Count,Information,Price,5_star,4_star,3_star,...,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments,Rating_count,Review_count
0,"Apple iPhone 15 (Black, 128 GB)",4.6,139977,4510,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770",...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ...",139977,4510
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,139977,4510,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770",...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ...",139977,4510

In [8]:
columns_to_remove = ['Rating Count','Rating_count', 'Review_count']
df.drop(columns=columns_to_remove, inplace=True)
df.head(2)

,Product Name,Rating,Rating_counts,Review_counts,Information,Price,5_star,4_star,3_star,2_star,...,Display_Negative_Score,Display_Comments,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments
0,"Apple iPhone 15 (Black, 128 GB)",4.6,139977,4510,"['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923",...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,139977,4510,"['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923",...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."

In [9]:
df['5_star'] = df['5_star'].str.replace(',','', regex=False)
df['5_star'] = pd.to_numeric(df['5_star'])
df['4_star'] = df['4_star'].str.replace(',','', regex=False)
df['4_star'] = pd.to_numeric(df['4_star'])
df['3_star'] = df['3_star'].str.replace(',','', regex=False)
df['3_star'] = pd.to_numeric(df['3_star'])
df['2_star'] = df['2_star'].str.replace(',','', regex=False)
df['2_star'] = pd.to_numeric(df['2_star'])
df['1_star'] = df['1_star'].str.replace(',','', regex=False)
df['1_star'] = pd.to_numeric(df['1_star'])
df.head(2)

,Product Name,Rating,Rating_counts,Review_counts,Information,Price,5_star,4_star,3_star,2_star,...,Display_Negative_Score,Display_Comments,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments
0,"Apple iPhone 15 (Black, 128 GB)",4.6,139977,4510,"['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,111018.0,16956.0,3770.0,1923.0,...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,139977,4510,"['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,111018.0,16956.0,3770.0,1923.0,...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."

In [10]:
col_of_overall_ratings = ["Camera_Overall_Rating",'Battery_Overall_Rating','Display_Overall_Rating','Design_Overall_Rating',
                         'Performance_Overall_Rating']
def overall_ratings_num(col):
    df[col] = pd.to_numeric(df[col], errors='coerce')  # Ensure numeric
    df[col] = df[col].fillna(0.5)  # Replace NaN with 0 (or another strategy)
    df[col] = df[col] / 5
for col in col_of_overall_ratings:
    overall_ratings_num(col)
df.head(2)

,Product Name,Rating,Rating_counts,Review_counts,Information,Price,5_star,4_star,3_star,2_star,...,Display_Negative_Score,Display_Comments,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments
0,"Apple iPhone 15 (Black, 128 GB)",4.6,139977,4510,"['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,111018.0,16956.0,3770.0,1923.0,...,3%,['...Battery - Better then other iphones 5/5\n...,0.92,96%,4%,['N/A'],0.92,96%,4%,"['...Osm performance', ""...The overall device ..."
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,139977,4510,"['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,111018.0,16956.0,3770.0,1923.0,...,3%,['...Battery - Better then other iphones 5/5\n...,0.92,96%,4%,['N/A'],0.92,96%,4%,"['...Osm performance', ""...The overall device ..."

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4877 entries, 0 to 4876
Data columns (total 31 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Product Name                4877 non-null   object
 1   Rating                      4877 non-null   float64
 2   Rating_counts               4877 non-null   int64
 3   Review_counts               4877 non-null   int64
 4   Information                 4877 non-null   object
 5   Price                       4877 non-null   int64
 6   5_star                      4857 non-null   float64
 7   4_star                      4857 non-null   float64
 8   3_star                      4857 non-null   float64
 9   2_star                      4857 non-null   float64
 10  1_star                      4857 non-null   float64
 11  Camera_Overall_Rating       4877 non-null   float64
 12  Camera_Positive_Score       4343 non-null   object
 13  Camera_Negative_Score       4343 non-null   object
 14  Camera_Comments             4343 non-null   object
 15  Battery_Overall_Rating      4877 non-null   float64
 16  Battery_Positive_Score      4349 non-null   object
 17  Battery_Negative_Score      4349 non-null   object
 18  Battery_Comments            4349 non-null   object
 19  Display_Overall_Rating      4877 non-null   float64
 20  Display_Positive_Score      4352 non-null   object
 21  Display_Negative_Score      4352 non-null   object
 22  Display_Comments            4352 non-null   object
 23  Design_Overall_Rating       4877 non-null   float64
 24  Design_Positive_Score       4520 non-null   object
 25  Design_Negative_Score       4520 non-null   object
 26  Design_Comments             4420 non-null   object
 27  Performance_Overall_Rating  4877 non-null   float64
 28  Performance_Positive_Score  4334 non-null   object
 29  Performance_Negative_Score  4334 non-null   object
 30  Performance_Comments        4334 non-null   object
dtypes: float64(11), int64(3), object(17)
memory usage: 1.2+ MB

In [12]:
# def score_num(col):
#     df[col] = df[col].str.replace('%','', regex=False) 
#     df[col] = pd.to_numeric(df[col], errors='coerce') 
#     df[col] = df[col].fillna(50) 
#     df[col] = df[col] / 100 
# list_col = [
#     "Camera_Positive_Score",
#     "Camera_Negative_Score",
#     "Battery_Positive_Score",
#     "Battery_Negative_Score",
#     "Display_Positive_Score",
#     "Display_Negative_Score",
#     "Design_Positive_Score",
#     "Design_Negative_Score",
#     "Performance_Positive_Score",
#     "Performance_Negative_Score"
# ]
# for col in list_col:
#     score_num(col)
# df['Any_Score_Missing'] = df[list_col].apply(lambda row: 1 if (row == 0.5).any() else 0, axis=1)
# df.head(2)
def score_num(col):
    df[col] = df[col].str.replace('%','', regex=False) 
    df[col] = pd.to_numeric(df[col], errors='coerce') 
    df[col] = df[col].fillna(50) 
    df[col] = df[col] / 100 
list_col = [
    "Camera_Positive_Score",
    "Camera_Negative_Score",
    "Battery_Positive_Score",
    "Battery_Negative_Score",
    "Display_Positive_Score",
    "Display_Negative_Score",
    "Design_Positive_Score",
    "Design_Negative_Score",
    "Performance_Positive_Score",
    "Performance_Negative_Score"
]
def calculate_missing_score(row):
    # Count 0.5 values only in these specific columns
    count_0_5 = sum(row[col] == 0.5 for col in list_col)
    
    if count_0_5 == 0:
        return 1.0
    elif count_0_5 == 1:
        return 0.7
    elif count_0_5 == 2:
        return 0.6
    elif count_0_5 == 3:
        return 0.5
    elif count_0_5 == 4:
        return 0.4
    else:
        return 0.3

# Apply the score_num function to all columns
for col in list_col:
    score_num(col)

# Calculate the Any_Score_Missing values based on only the 8 specific columns
df['Any_Score_Missing'] = df.apply(calculate_missing_score, axis=1)

In [13]:
def star_na_fill(col):
    df[col] = df[col].fillna(0)
star_col = ["5_star","4_star","3_star","2_star","1_star"]
for col  in star_col:
    star_na_fill(col)

In [14]:
numeric_df = df.select_dtypes(include=np.number)
numeric_df.head(2)

,Rating,Rating_counts,Review_counts,Price,5_star,4_star,3_star,2_star,1_star,Camera_Overall_Rating,...,Display_Overall_Rating,Display_Positive_Score,Display_Negative_Score,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Any_Score_Missing
0,4.6,139977,4510,57999,111018.0,16956.0,3770.0,1923.0,6310.0,0.92,...,0.92,0.97,0.03,0.92,0.96,0.04,0.92,0.96,0.04,0.6
1,4.6,139977,4510,57999,111018.0,16956.0,3770.0,1923.0,6310.0,0.92,...,0.92,0.97,0.03,0.92,0.96,0.04,0.92,0.96,0.04,0.6

In [15]:
# import seaborn as sns
# import matplotlib.pyplot as plt

# corr_matrix = numeric_df.corr()
# sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
# plt.show()
# corr_matrix
features = [
    'Rating','Rating_counts', 'Review_counts', 
    'Price', "5_star", "4_star", "3_star", "2_star", "1_star",
]
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

# Function to scale specified columns
def scaling(df, cols):
    df[cols] = scaler.fit_transform(df[cols])

# Scale the features
scaling(numeric_df, features)

In [16]:
numeric_df["Any_Score_Missing"].value_counts()

Any_Score_Missing
1.0    2502
0.6    1321
0.3     608
0.4     446
Name: count, dtype: int64

In [17]:
numeric_df.insert(0, "Mobile_name", df["Product Name"])
numeric_df.head(2)

,Mobile_name,Rating,Rating_counts,Review_counts,Price,5_star,4_star,3_star,2_star,1_star,...,Display_Overall_Rating,Display_Positive_Score,Display_Negative_Score,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Any_Score_Missing
0,"Apple iPhone 15 (Black, 128 GB)",0.878788,0.113778,0.030118,0.311069,0.125508,0.075145,0.058296,0.079766,0.107275,...,0.92,0.97,0.03,0.92,0.96,0.04,0.92,0.96,0.04,0.6
1,"Apple iPhone 15 (Pink, 128 GB)",0.878788,0.113778,0.030118,0.311069,0.125508,0.075145,0.058296,0.079766,0.107275,...,0.92,0.97,0.03,0.92,0.96,0.04,0.92,0.96,0.04,0.6

In [18]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import StandardScaler
# Compute the cosine similarity matrix
temp = numeric_df.iloc[:,1:]
similarity_matrix = cosine_similarity(temp)

# Convert the similarity matrix into a DataFrame for easier interpretation
similarity_df = pd.DataFrame(similarity_matrix, index=df["Product Name"], columns=df["Product Name"])

In [19]:
def recommend_products(product_name, similarity_df, top_n=5):
    # Get the similarity scores for the given product
    similar_scores = similarity_df[product_name].sort_values(ascending=False)
    
    # Exclude the product itself (i.e., the first value in the similarity score)
    similar_scores = similar_scores.drop(product_name)
    
    # Get the top N similar products
    top_recommendations = similar_scores.head(top_n)
    
    return top_recommendations

In [20]:
recommend_products("Nothing Phone (2a) Plus (Black, 256 GB)", similarity_df, top_n=5)

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'

In [21]:
similarity_df.shape

(4877, 4877)

In [22]:
df.sample(10)

,Product Name,Rating,Rating_counts,Review_counts,Information,Price,5_star,4_star,3_star,2_star,...,Display_Comments,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments,Any_Score_Missing
1827,"LAVA Z6 (Flame Red, 128 GB)",4.1,510,64,['6 GB RAM | 128 GB ROM | Expandable Upto 512 ...,11499,294.0,88.0,51.0,17.0,...,['N/A'],0.78,0.82,0.18,['N/A'],0.64,0.62,0.38,['N/A'],1.0
2846,"OnePlus 9RT 5G (Nano Silver, 256 GB)",4.0,303,28,"['12 GB RAM | 256 GB ROM', '16.81 cm (6.62 inc...",44998,175.0,62.0,13.0,10.0,...,NaN,0.84,0.90,0.10,['...Slow Processor plz improvement\nAndroid v...,0.10,0.50,0.50,NaN,0.3
933,"Infinix GT 20 Pro (Mecha Orange, 256 GB)",4.3,6012,418,"['12 GB RAM | 256 GB ROM', '17.22 cm (6.78 inc...",25999,3959.0,1028.0,352.0,170.0,...,"['...It is not AMOLED FULL HD, it is a cheap 3...",0.90,0.94,0.06,['N/A'],0.86,0.91,0.09,['...converts sdr to hdr\nSound: 5/5 Thanks to...,0.6
2701,"OnePlus 12R (Cool Blue, 256 GB)",4.5,3257,199,"['16 GB RAM | 256 GB ROM', '17.22 cm (6.78 inc...",41988,2346.0,556.0,133.0,52.0,...,NaN,0.10,0.50,0.50,Error,0.10,0.50,0.50,NaN,0.3
3593,"realme 10 (Clash White, 128 GB)",4.3,12733,865,['8 GB RAM | 128 GB ROM | Expandable Upto 1 TB...,19999,7906.0,2768.0,886.0,341.0,...,['...Adorable phone.the display is quite good ...,0.86,0.93,0.07,['N/A'],0.10,0.50,0.50,Error,0.6
1528,KARBONN K9 Yuva Keypad Mobile| 2500 mAh Batter...,3.8,1981,119,"['64 MB RAM | 32 KB ROM', '4.57 cm (1.8 inch) ...",1099,1011.0,294.0,208.0,134.0,...,['N/A'],0.66,0.71,0.29,['N/A'],0.64,0.62,0.38,['N/A'],1.0
1559,KARBONN KX51PRO,3.7,15,2,"['32 MB RAM | 32 MB ROM', '6.1 cm (2.4 inch) D...",1069,7.0,3.0,2.0,0.0,...,NaN,0.10,0.50,0.50,NaN,0.66,0.70,0.30,['N/A'],0.3
2241,"Motorola e13 (Cosmic Black, 64 GB)",4.1,105371,7782,['4 GB RAM | 64 GB ROM | Expandable Upto 1 TB'...,10999,55736.0,25348.0,10992.0,4313.0,...,Error,0.80,0.88,0.12,['N/A'],0.72,0.80,0.20,"['...The performance wise phone is slow.', '.....",0.6
1498,itel it5330 | 2.8 inch Big Display | 1900 mAh ...,4.1,7375,399,['32 MB RAM | 32 MB ROM | Expandable Upto 32 G...,1349,3927.0,1704.0,747.0,322.0,...,"['...Very light weight.\nBest Performance,\nDi...",0.84,0.89,0.11,['N/A'],0.76,0.83,0.17,['N/A'],0.4
4279,"Xiaomi 11i Hypercharge 5G (Stealth Black, 128 GB)",4.2,7270,764,['8 GB RAM | 128 GB ROM | Expandable Upto 1 TB...,28999,4474.0,1416.0,509.0,209.0,...,['...Quick charging technology great\nDisplay ...,0.78,0.86,0.14,['N/A'],0.78,0.86,0.14,['...superb performance 632 is good processor....,0.6

In [23]:
product_name = "Nothing Phone (2a) Plus (Black, 256 GB)"
if product_name in similarity_df.index and product_name in similarity_df.columns:
    print(f"{product_name} is valid and present.")
else:
    print(f"{product_name} is not found in similarity_df.")

Nothing Phone (2a) Plus (Black, 256 GB) is valid and present.

In [24]:
print(similarity_df.isnull().sum().sum())  # Check for missing values
print(similarity_df.shape)  # Ensure rows and columns align

0
(4877, 4877)

In [25]:
duplicates = similarity_df.index[similarity_df.index.duplicated()].unique()
if len(duplicates) > 0:
    print(f"Duplicate products found: {duplicates}")

Duplicate products found: Index(['ASUS Zenfone 4 (White, 8 GB)', 'ASUS Zenfone 4 (Yellow, 8 GB)',
       'ASUS Zenfone 4 (Red, 8 GB)', 'ASUS Zenfone 4 (Blue, 8 GB)',
       'ASUS Zenfone 4 (Black, 8 GB)', 'ASUS Zenfone 5 A501CG (Gold, 8 GB)',
       'ASUS ZenFone Max Pro M2 (Titanium, 64 GB)',
       'ASUS ZenFone Max Pro M2 (Blue, 64 GB)',
       'ASUS Zenfone Max Pro M1 (Blue, 64 GB)',
       'ASUS Zenfone Max Pro M1 (Grey, 64 GB)',
       ...
       'vivo T1 Pro 5G (Turbo Cyan, 128 GB)',
       'vivo T1 5G (Silky White, 128 GB)', 'vivo Z1Pro (Sonic Blue, 64 GB)',
       'vivo Y20 (Obsidian Black, 64 GB)',
       'vivo Y51A (Titanium Sapphire, 128 GB)',
       'vivo Y51A (Crystal Symphony, 128 GB)', 'vivo Y91i (Ocean Blue, 32 GB)',
       'vivo V15 Pro (Topaz Blue, 128 GB)',
       'vivo V27 5G (Noble Black, 256 GB)', 'vivo Z1x (Fusion Blue, 128 GB)'],
      dtype='object', name='Product Name', length=644)

In [26]:
first_column_df = similarity_df.iloc[:, :2]
first_column_df

Product Name,"Apple iPhone 15 (Black, 128 GB)","Apple iPhone 15 (Pink, 128 GB)"
Product Name,,
"Apple iPhone 15 (Black, 128 GB)",1.000000,1.000000
"Apple iPhone 15 (Pink, 128 GB)",1.000000,1.000000
"Apple iPhone 15 (Green, 128 GB)",1.000000,1.000000
"Apple iPhone 15 (Blue, 128 GB)",1.000000,1.000000
"Apple iPhone 15 Plus (Blue, 128 GB)",0.875357,0.875357
...,...,...
"vivo X60 Pro (Shimmer Blue, 256 GB)",0.811380,0.811380
"vivo Y11 (Mineral Blue, 32 GB)",0.867155,0.867155
"vivo V20 SE (Aquamarine Green, 128 GB)",0.804208,0.804208
"vivo V20 SE (Gravity Black, 128 GB)",0.804208,0.804208
"vivo U20 (Blaze Blue, 128 GB)",0.701186,0.701186

In [27]:
df['Product Name'].duplicated().sum()

999

In [28]:
    df['Product Name']

0              Apple iPhone 15 (Black, 128 GB)
1               Apple iPhone 15 (Pink, 128 GB)
2              Apple iPhone 15 (Green, 128 GB)
3               Apple iPhone 15 (Blue, 128 GB)
4          Apple iPhone 15 Plus (Blue, 128 GB)
                         ...
4872       vivo X60 Pro (Shimmer Blue, 256 GB)
4873            vivo Y11 (Mineral Blue, 32 GB)
4874    vivo V20 SE (Aquamarine Green, 128 GB)
4875       vivo V20 SE (Gravity Black, 128 GB)
4876             vivo U20 (Blaze Blue, 128 GB)
Name: Product Name, Length: 4877, dtype: object