In [1]:
import pandas as pd
import os

# Directory containing the CSV files
csv_dir = "C:/Users/Admin/Desktop/Lab Exam/86955_Python_R_programming/Final csv"

# List to store DataFrames
dataframes = []

# Iterate through all CSV files in the directory
for file in os.listdir(csv_dir):
    if file.endswith(".csv"):
        print(file)
        file_path = os.path.join(csv_dir, file)
        df = pd.read_csv(file_path)
        dataframes.append(df)
# print(dataframes)
combined_df = pd.concat(dataframes, ignore_index=True)

output_file = "combined_data.csv"
combined_df.to_csv(output_file, index=False)

print(f"Combined CSV saved")

apple_with_ratings_and_feature_hrefs.csv
Asus_with_ratings_and_feature_hrefs.csv
Honor_with_ratings_and_feature_hrefs.csv
HTC_with_ratings_and_feature_hrefs.csv
Infinix_with_ratings_and_feature_hrefs.csv
iQ_with_ratings_and_feature_hrefs.csv
Itel_with_ratings_and_feature_hrefs.csv
Karbon_with_ratings_and_feature_hrefs.csv
Lava_with_ratings_and_feature_hrefs.csv
Lenovo_with_ratings_and_feature_hrefs.csv
Micromax_with_ratings_and_feature_hrefs.csv
Motorola_with_ratings_and_feature_hrefs.csv
NOKIA_with_ratings_and_feature_hrefs.csv
Nothing_with_ratings_and_feature_hrefs.csv
OnePlus_with_camera_ratings_and_comments.csv
Oppo_with_ratings_and_feature_hrefs.csv
Poco_with_ratings_and_feature_hrefs.csv
Realme_with_ratings_and_feature_hrefs.csv
Redmi_with_ratings_and_feature_hrefs.csv
Sony_with_ratings_and_feature_hrefs.csv
Techno_with_ratings_and_feature_hrefs.csv
Vivo_with_ratings_and_feature_hrefs.csv
Combined CSV saved

In [62]:
import numpy as np
df = pd.read_csv("combined_data.csv")
df.head(2)

,Product Name,Rating,Rating Count,Information,Price,href,5_star,4_star,3_star,2_star,...,Display_Negative_Score,Display_Comments,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments
0,"Apple iPhone 15 (Black, 128 GB)",4.6,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...","₹57,999",https://www.flipkart.com/apple-iphone-15-black...,"1,11,018","16,956","3,770","1,923",...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...","₹57,999",https://www.flipkart.com/apple-iphone-15-pink-...,"1,11,018","16,956","3,770","1,923",...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."

In [63]:
df['Product Name'] = df['Product Name'] + ' ' + df['Price'].astype(str)

In [64]:
df.shape

(4877, 37)

In [65]:
columns_to_remove = ['href','Camera_href', 'Battery_href', 'Display_href',  'Design_href', 'overall_href', 'performance_href']
df.drop(columns=columns_to_remove, inplace=True)
df.head(2)

,Product Name,Rating,Rating Count,Information,Price,5_star,4_star,3_star,2_star,1_star,...,Display_Negative_Score,Display_Comments,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments
0,"Apple iPhone 15 (Black, 128 GB) ₹57,999",4.6,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...","₹57,999","1,11,018","16,956","3,770","1,923","6,310",...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."
1,"Apple iPhone 15 (Pink, 128 GB) ₹57,999",4.6,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...","₹57,999","1,11,018","16,956","3,770","1,923","6,310",...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."

In [68]:
df1 = df.iloc[:,:1]
df1.duplicated().sum()

342

In [5]:
df['Price'] = df['Price'].str.replace('₹','', regex=False)
df['Price'] = df['Price'].str.replace(',','', regex=False)
df['Price'] = pd.to_numeric(df['Price'])
df.head(2)

,Product Name,Rating,Rating Count,Information,Price,5_star,4_star,3_star,2_star,1_star,...,Display_Negative_Score,Display_Comments,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments
0,"Apple iPhone 15 (Black, 128 GB)",4.6,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923","6,310",...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923","6,310",...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."

In [6]:
import pandas as pd
import re

# Function to extract ratings and reviews
def extract_ratings_reviews(row):
    # Extract ratings
    ratings_match = re.search(r'([\d,]+) Ratings', row)
    ratings = int(ratings_match.group(1).replace(',', '')) if ratings_match else 0
    
    # Extract reviews
    reviews_match = re.search(r'([\d,]+) Reviews', row)
    reviews = int(reviews_match.group(1).replace(',', '')) if reviews_match else 0
    
    return pd.Series({'Rating_count': ratings, 'Review_count': reviews})

# # Example DataFrame
# data = {'Details': ['1,39,977 Ratings & 4,510 Reviews', '5,000 Ratings & 350 Reviews']}
# df = pd.DataFrame(data)

# Apply the function to create new columns
df[['Rating_count', 'Review_count']] = df['Rating Count'].apply(extract_ratings_reviews)

df.head(2)

,Product Name,Rating,Rating Count,Information,Price,5_star,4_star,3_star,2_star,1_star,...,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments,Rating_count,Review_count
0,"Apple iPhone 15 (Black, 128 GB)",4.6,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923","6,310",...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ...",139977,4510
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923","6,310",...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ...",139977,4510

In [7]:
df.insert(2, "Rating_counts", df['Rating_count'])
df.head()

,Product Name,Rating,Rating_counts,Rating Count,Information,Price,5_star,4_star,3_star,2_star,...,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments,Rating_count,Review_count
0,"Apple iPhone 15 (Black, 128 GB)",4.6,139977,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923",...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ...",139977,4510
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,139977,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923",...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ...",139977,4510
2,"Apple iPhone 15 (Green, 128 GB)",4.6,139977,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923",...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ...",139977,4510
3,"Apple iPhone 15 (Blue, 128 GB)",4.6,139977,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",58249,"1,11,018","16,956","3,770","1,923",...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ...",139977,4510
4,"Apple iPhone 15 Plus (Blue, 128 GB)",4.6,21881,"21,881 Ratings & 1,151 Reviews","['128 GB ROM', '17.02 cm (6.7 inch) Super Reti...",66999,"17,326","2,833",544,261,...,4.6,97%,3%,['N/A'],Error,Error,Error,Error,21881,1151

In [8]:
df.insert(3, "Review_counts", df['Review_count'])
df.head(2)

,Product Name,Rating,Rating_counts,Review_counts,Rating Count,Information,Price,5_star,4_star,3_star,...,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments,Rating_count,Review_count
0,"Apple iPhone 15 (Black, 128 GB)",4.6,139977,4510,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770",...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ...",139977,4510
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,139977,4510,"1,39,977 Ratings & 4,510 Reviews","['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770",...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ...",139977,4510

In [10]:
columns_to_remove = ['Rating Count','Rating_count', 'Review_count']
df.drop(columns=columns_to_remove, inplace=True)
df.head(2)

,Product Name,Rating,Rating_counts,Review_counts,Information,Price,5_star,4_star,3_star,2_star,...,Display_Negative_Score,Display_Comments,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments
0,"Apple iPhone 15 (Black, 128 GB)",4.6,139977,4510,"['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923",...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,139977,4510,"['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,"1,11,018","16,956","3,770","1,923",...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."

In [11]:
df['5_star'] = df['5_star'].str.replace(',','', regex=False)
df['5_star'] = pd.to_numeric(df['5_star'])
df['4_star'] = df['4_star'].str.replace(',','', regex=False)
df['4_star'] = pd.to_numeric(df['4_star'])
df['3_star'] = df['3_star'].str.replace(',','', regex=False)
df['3_star'] = pd.to_numeric(df['3_star'])
df['2_star'] = df['2_star'].str.replace(',','', regex=False)
df['2_star'] = pd.to_numeric(df['2_star'])
df['1_star'] = df['1_star'].str.replace(',','', regex=False)
df['1_star'] = pd.to_numeric(df['1_star'])
df.head(2)

,Product Name,Rating,Rating_counts,Review_counts,Information,Price,5_star,4_star,3_star,2_star,...,Display_Negative_Score,Display_Comments,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments
0,"Apple iPhone 15 (Black, 128 GB)",4.6,139977,4510,"['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,111018.0,16956.0,3770.0,1923.0,...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,139977,4510,"['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,111018.0,16956.0,3770.0,1923.0,...,3%,['...Battery - Better then other iphones 5/5\n...,4.6,96%,4%,['N/A'],4.6,96%,4%,"['...Osm performance', ""...The overall device ..."

In [12]:
col_of_overall_ratings = ["Camera_Overall_Rating",'Battery_Overall_Rating','Display_Overall_Rating','Design_Overall_Rating',
                         'Performance_Overall_Rating']
def overall_ratings_num(col):
    df[col] = pd.to_numeric(df[col], errors='coerce')  # Ensure numeric
    df[col] = df[col].fillna(0.5)  # Replace NaN with 0 (or another strategy)
    df[col] = df[col] / 5
for col in col_of_overall_ratings:
    overall_ratings_num(col)
df.head(2)

,Product Name,Rating,Rating_counts,Review_counts,Information,Price,5_star,4_star,3_star,2_star,...,Display_Negative_Score,Display_Comments,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Design_Comments,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Performance_Comments
0,"Apple iPhone 15 (Black, 128 GB)",4.6,139977,4510,"['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,111018.0,16956.0,3770.0,1923.0,...,3%,['...Battery - Better then other iphones 5/5\n...,0.92,96%,4%,['N/A'],0.92,96%,4%,"['...Osm performance', ""...The overall device ..."
1,"Apple iPhone 15 (Pink, 128 GB)",4.6,139977,4510,"['128 GB ROM', '15.49 cm (6.1 inch) Super Reti...",57999,111018.0,16956.0,3770.0,1923.0,...,3%,['...Battery - Better then other iphones 5/5\n...,0.92,96%,4%,['N/A'],0.92,96%,4%,"['...Osm performance', ""...The overall device ..."

In [14]:
def score_num(col):
    df[col] = df[col].str.replace('%','', regex=False) 
    df[col] = pd.to_numeric(df[col], errors='coerce') 
    df[col] = df[col].fillna(50) 
    df[col] = df[col] / 100 
list_col = [
    "Camera_Positive_Score",
    "Camera_Negative_Score",
    "Battery_Positive_Score",
    "Battery_Negative_Score",
    "Display_Positive_Score",
    "Display_Negative_Score",
    "Design_Positive_Score",
    "Design_Negative_Score",
    "Performance_Positive_Score",
    "Performance_Negative_Score"
]
def calculate_missing_score(row):
    # Count 0.5 values only in these specific columns
    count_0_5 = sum(row[col] == 0.5 for col in list_col)
    
    if count_0_5 == 0:
        return 1.0
    elif count_0_5 == 1:
        return 0.7
    elif count_0_5 == 2:
        return 0.6
    elif count_0_5 == 3:
        return 0.5
    elif count_0_5 == 4:
        return 0.4
    else:
        return 0.3

# Apply the score_num function to all columns
for col in list_col:
    score_num(col)

# Calculate the Any_Score_Missing values based on only the 8 specific columns
df['Any_Score_Missing'] = df.apply(calculate_missing_score, axis=1)

In [16]:
def star_na_fill(col):
    df[col] = df[col].fillna(0)
star_col = ["5_star","4_star","3_star","2_star","1_star"]
for col  in star_col:
    star_na_fill(col)

In [18]:
numeric_df = df.select_dtypes(include=np.number)
numeric_df.head(2)

,Rating,Rating_counts,Review_counts,Price,5_star,4_star,3_star,2_star,1_star,Camera_Overall_Rating,...,Display_Overall_Rating,Display_Positive_Score,Display_Negative_Score,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Any_Score_Missing
0,4.6,139977,4510,57999,111018.0,16956.0,3770.0,1923.0,6310.0,0.92,...,0.92,0.97,0.03,0.92,0.96,0.04,0.92,0.96,0.04,0.6
1,4.6,139977,4510,57999,111018.0,16956.0,3770.0,1923.0,6310.0,0.92,...,0.92,0.97,0.03,0.92,0.96,0.04,0.92,0.96,0.04,0.6

In [20]:
features = [
    'Rating','Rating_counts', 'Review_counts', 
    'Price', "5_star", "4_star", "3_star", "2_star", "1_star",
]
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

# Function to scale specified columns
def scaling(df, cols):
    df[cols] = scaler.fit_transform(df[cols])

# Scale the features
scaling(numeric_df, features)

In [22]:
numeric_df["Any_Score_Missing"].value_counts()

Any_Score_Missing
1.0    2502
0.6    1321
0.3     608
0.4     446
Name: count, dtype: int64

In [28]:
numeric_df.insert(0, "Mobile_name", df["Product Name"])
numeric_df.head(2)

,Mobile_name,Rating,Rating_counts,Review_counts,Price,5_star,4_star,3_star,2_star,1_star,...,Display_Overall_Rating,Display_Positive_Score,Display_Negative_Score,Design_Overall_Rating,Design_Positive_Score,Design_Negative_Score,Performance_Overall_Rating,Performance_Positive_Score,Performance_Negative_Score,Any_Score_Missing
0,"Apple iPhone 15 (Black, 128 GB)",0.878788,0.113778,0.030118,0.311069,0.125508,0.075145,0.058296,0.079766,0.107275,...,0.92,0.97,0.03,0.92,0.96,0.04,0.92,0.96,0.04,0.6
1,"Apple iPhone 15 (Pink, 128 GB)",0.878788,0.113778,0.030118,0.311069,0.125508,0.075145,0.058296,0.079766,0.107275,...,0.92,0.97,0.03,0.92,0.96,0.04,0.92,0.96,0.04,0.6

In [35]:
output_file = "numeric.csv"
numeric_df.to_csv(output_file, index=False)

In [36]:
numeric_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4877 entries, 0 to 4876
Data columns (total 26 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Mobile_name                 4877 non-null   object
 1   Rating                      4877 non-null   float64
 2   Rating_counts               4877 non-null   float64
 3   Review_counts               4877 non-null   float64
 4   Price                       4877 non-null   float64
 5   5_star                      4877 non-null   float64
 6   4_star                      4877 non-null   float64
 7   3_star                      4877 non-null   float64
 8   2_star                      4877 non-null   float64
 9   1_star                      4877 non-null   float64
 10  Camera_Overall_Rating       4877 non-null   float64
 11  Camera_Positive_Score       4877 non-null   float64
 12  Camera_Negative_Score       4877 non-null   float64
 13  Battery_Overall_Rating      4877 non-null   float64
 14  Battery_Positive_Score      4877 non-null   float64
 15  Battery_Negative_Score      4877 non-null   float64
 16  Display_Overall_Rating      4877 non-null   float64
 17  Display_Positive_Score      4877 non-null   float64
 18  Display_Negative_Score      4877 non-null   float64
 19  Design_Overall_Rating       4877 non-null   float64
 20  Design_Positive_Score       4877 non-null   float64
 21  Design_Negative_Score       4877 non-null   float64
 22  Performance_Overall_Rating  4877 non-null   float64
 23  Performance_Positive_Score  4877 non-null   float64
 24  Performance_Negative_Score  4877 non-null   float64
 25  Any_Score_Missing           4877 non-null   float64
dtypes: float64(25), object(1)
memory usage: 990.8+ KB

In [1]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
data = pd.read_csv("numeric.csv")  # Replace with your file
features = [
    'Rating', 'Rating_counts', 'Review_counts', 'Price',
    '5_star', '4_star', '3_star', '2_star', '1_star',
    'Camera_Overall_Rating', 'Camera_Positive_Score', 'Camera_Negative_Score',
    'Battery_Overall_Rating', 'Battery_Positive_Score', 'Battery_Negative_Score',
    'Display_Overall_Rating', 'Display_Positive_Score', 'Display_Negative_Score',
    'Design_Overall_Rating', 'Design_Positive_Score', 'Design_Negative_Score',
    'Performance_Overall_Rating', 'Performance_Positive_Score', 'Performance_Negative_Score', 'Any_Score_Missing'
]
similarity_matrix = cosine_similarity(data[features])
similarity_df = pd.DataFrame(similarity_matrix)
similarity_df.to_csv('similarity_matrix.csv', index=False)
similarity_df.head(2)

,0,1,2,3,4,5,6,7,8,9,...,4867,4868,4869,4870,4871,4872,4873,4874,4875,4876
0,1.0,1.0,1.0,1.0,0.875357,0.875357,0.875357,0.999837,0.999837,0.875357,...,0.860555,0.700536,0.878716,0.867155,0.81138,0.81138,0.867155,0.804208,0.804208,0.701186
1,1.0,1.0,1.0,1.0,0.875357,0.875357,0.875357,0.999837,0.999837,0.875357,...,0.860555,0.700536,0.878716,0.867155,0.81138,0.81138,0.867155,0.804208,0.804208,0.701186

In [12]:
def recommend_mobile(user_input, df, similarity_df):
    unique_names = df['Mobile_name'].unique()
    if user_input not in unique_names:
        print("Mobile name not found.")
        return []
    index = df[df['Mobile_name'] == user_input].index[0]
    similarity_scores = similarity_df.iloc[index]
    top_indices = similarity_scores.nlargest(11).index[1:]  
    recommended_mobiles = df.iloc[top_indices]['Mobile_name'].tolist()
    recommended_set = set(recommended_mobiles)
    recommended_set.discard(user_input) 
    return list(recommended_set)[:5]
    
user_input = 'Infinix Smart 7 HD (Green Apple, 64 GB)'
recommendations = recommend_mobile(user_input, data, similarity_df)
print(recommendations)

['Motorola e13 (Aurora Green, 64 GB)', 'Motorola e13 (Cosmic Black, 64 GB)', 'Infinix Smart 7 HD (Ink Black, 64 GB)', 'REDMI A3 (Midnight Black, 128 GB)', 'Infinix HOT 30i (Mirror Black, 64 GB)']

In [14]:
i = 0
for mobile in data['Mobile_name'][600:]:
    rec = recommend_mobile(mobile, data, similarity_df)
    print(f"{mobile} :: {rec[0]}")
    print(f"2) :: {rec[1]}")
    print(f"3) :: {rec[2]}")
    print(f"4) :: {rec[3]}")
    print(f"5) :: {rec[4]}")
    i=i+1
    if i> 10:
        break

ASUS ZenFone 5Z (Midnight Blue, 128 GB) :: realme 10 Pro+ 5G (Nebula Blue, 128 GB)
2) :: realme P2 Pro 5G (Eagle Grey, 256 GB)
3) :: Motorola Edge 50 Neo (PANTONE Poinciana, 256 GB)
4) :: IQOO 7 5G (Monster Orange, 128 GB)
5) :: ASUS ZenFone 5Z (Midnight Blue, 64 GB)
ASUS ZenFone Lite L1 (Gold, 16 GB) :: POCO M6 Pro 5G (Forest Green, 128 GB)
2) :: realme C2 (Diamond Black, 32 GB)
3) :: Motorola G34 5G (Ocean Green, 128 GB)
4) :: realme C53 (Champion Gold, 128 GB)
5) :: Motorola G34 5G (Ice Blue, 128 GB)
ASUS ZenFone 5Z (Midnight Blue, 64 GB) :: realme 10 Pro+ 5G (Nebula Blue, 128 GB)
2) :: realme P2 Pro 5G (Eagle Grey, 256 GB)
3) :: ASUS ZenFone 5Z (Midnight Blue, 128 GB)
4) :: realme X2 (Pearl White, 64 GB)
5) :: IQOO 7 5G (Monster Orange, 128 GB)
ASUS ZenFone 5Z (Midnight Blue, 256 GB) :: REDMI Note 13 Pro 5G (Midnight Black, 256 GB)
2) :: REDMI Note 13 Pro 5G (Coral Purple, 256 GB)
3) :: REDMI Note 13 Pro 5G (Arctic White, 256 GB)
4) :: ASUS ZenFone 5Z (Meteor Silver, 64 GB)
5) :: Honor 10 Lite (Midnight Black, 32 GB)
ASUS ZenFone 5Z (Meteor Silver, 256 GB) :: REDMI Note 13 Pro 5G (Coral Purple, 256 GB)
2) :: Honor 8x (Black, 64 GB)
3) :: ASUS ZenFone 5Z (Meteor Silver, 64 GB)
4) :: realme X7 Max (Asteroid Black, 256 GB)
5) :: Honor 8X (Blue, 64 GB)
ASUS 6Z (Silver, 128 GB) :: ASUS 6Z (Silver, 256 GB)
2) :: Mi 10T (Cosmic Black, 128 GB)
3) :: Honor 20 (Sapphire Blue, 128 GB)
4) :: IQOO Z3 5G (Ace Black, 256 GB)
5) :: REDMI Note 9 Pro Max (Champagne Gold, 128 GB)
ASUS ZenFone Max Pro M2 (Titanium, 64 GB) :: REDMI NOTE 10 LITE (Champagne Gold, 128 GB)
2) :: Infinix Note 5 (Ice Blue, 64 GB)
3) :: vivo Y30 (Emerald Black, 128 GB)
4) :: Infinix Note 7 (Bolivia Blue, 64 GB)
5) :: Infinix Note 12 TURBO (Force Black, 128 GB)
ASUS ZenFone Max Pro M2 (Blue, 64 GB) :: Motorola g54 5G (Mint Green, 256 GB)
2) :: realme Narzo 30 Pro 5G (Sword Black, 64 GB)
3) :: realme 8 5G (Supersonic Black, 64 GB)
4) :: Infinix Hot 11S (Polar Black, 128 GB)
5) :: realme 7 Pro (Mirror Silver, 128 GB)
ASUS ZenFone 5Z (Meteor Silver, 64 GB) :: REDMI Note 13 Pro 5G (Coral Purple, 256 GB)
2) :: REDMI Note 13 Pro 5G (Midnight Black, 128 GB)
3) :: Honor 8x (Black, 64 GB)
4) :: ASUS ZenFone 5Z (Midnight Blue, 64 GB)
5) :: Honor 10 Lite (Midnight Black, 32 GB)
ASUS ZenFone 5Z (Meteor Silver, 128 GB) :: REDMI Note 13 Pro 5G (Scarlet Red, 128 GB)
2) :: REDMI Note 13 Pro 5G (Coral Purple, 256 GB)
3) :: REDMI Note 13 Pro 5G (Midnight Black, 128 GB)
4) :: ASUS ZenFone 5Z (Meteor Silver, 64 GB)
5) :: Honor 8x (Black, 64 GB)
ASUS 6Z (Black, 128 GB) :: Apple IPhone 4 (Black, 8 GB)
2) :: Honor 7 (Fantasy Silver, 16 GB)
3) :: REDMI Note 13 Pro 5G (Arctic White, 256 GB)
4) :: SONY Xperia Z3 (Black, 16 GB)
5) :: Honor 200 5G (Moonlight White, 512 GB)

In [47]:
# # Convert similarity matrix to a DataFrame
# similarity_df = pd.DataFrame(similarity_matrix, 
#                              index=data['Mobile_name'], 
#                              columns=data['Mobile_name'])

# # Save to a CSV file
# similarity_df.to_csv("similarity_matrix.csv")
# print("Similarity matrix saved successfully!")

Similarity matrix saved successfully!

In [48]:
# Load the similarity matrix
# similarity_df = pd.read_csv("similarity_matrix.csv", index_col=0)

In [71]:
# # Example: Get similar products for a given mobile
# def recommend_from_saved_matrix(mobile_name, similarity_df, top_n=5):
#     if mobile_name not in similarity_df.index:
#         return f"{mobile_name} not found in the dataset."
    
#     # Get similarity scores for the given mobile
#     similarity_scores = similarity_df.loc[mobile_name].sort_values(ascending=False)
    
#     # Exclude the input mobile and get top n recommendations
#     recommended_mobiles = similarity_scores.index[1:top_n+1].tolist()
#     return recommended_mobiles

# # Test the function
# mobile_name = "Micromax S116"  # Replace with a mobile from your dataset
# recommendations = recommend_from_saved_matrix(mobile_name, similarity_df)
# print("Recommended Mobiles:", recommendations)

In [72]:
# # Add a unique identifier to the mobile names to resolve duplicates
# data['Unique_Mobile_Name'] = data['Mobile_name'] + " (" + data.index.astype(str) + ")"

# # Recompute the similarity matrix with the unique names
# similarity_df1 = pd.DataFrame(similarity_matrix, 
#                              index=data['Unique_Mobile_Name'], 
#                              columns=data['Unique_Mobile_Name'])

# # Save the updated similarity matrix
# similarity_df1.to_csv("similarity_matrix_unique.csv")
# print("Similarity matrix with unique mobile names saved successfully!")

In [60]:
# # Load the similarity matrix with unique names
# similarity_df = pd.read_csv("similarity_matrix_unique.csv", index_col=0)

# # Function to recommend similar mobiles
# def recommend_from_saved_matrix(mobile_name, data, similarity_df, top_n=5):
#     # Find unique name corresponding to the input mobile name
#     unique_names = data[data['Mobile_name'] == mobile_name]['Unique_Mobile_Name'].values
    
#     if len(unique_names) == 0:
#         return f"{mobile_name} not found in the dataset."
#     elif len(unique_names) > 1:
#         return f"Multiple entries found for {mobile_name}: {unique_names}"
    
#     unique_mobile_name = unique_names[0]
    
#     # Get similarity scores for the given mobile
#     similarity_scores = similarity_df.loc[unique_mobile_name].sort_values(ascending=False)
    
#     # Exclude the input mobile and get top n recommendations
#     recommended_indices = similarity_scores.index[1:top_n+1].tolist()
    
#     # Map unique names back to original mobile names
#     recommended_mobiles = data[data['Unique_Mobile_Name'].isin(recommended_indices)]['Mobile_name'].tolist()
#     return recommended_mobiles

# # Test the function
# mobile_name = "Micromax S116"  # Replace with a mobile from your dataset
# recommendations = recommend_from_saved_matrix(mobile_name, data, similarity_df)
# print("Recommended Mobiles:", recommendations)

Recommended Mobiles: Multiple entries found for Micromax S116: ['Micromax S116 (2085)' 'Micromax S116 (2086)']

In [73]:
# similarity_df.head()